### ISSUE TITLE
How can get tracker list for dht network(metadata)

### ISSUE THREAD

**Issue by senioi** [ruslanfedoseenko/dhtcrawler#1]
If not have this tracker list, torrent clients cannot download files from this magnet link
And , Can you share script files for PostgreSQL tables and columns?
Thank you,
Have a good day.

**Comment by devrus91** [comment]
There is some known dht bootsrap nodes i use this one:
- "router.bittorrent.com:6881",
- "router.utorrent.com:6881",
- "dht.transmissionbt.com:6881".

Here is pg_dump of schema
[torrents.zip](https://github.com/ruslanfedoseenko/dhtcrawler/files/2296976/torrents.zip)

This app is currently running here [btoogle.com](https://btoogle.com)
